# Site settings
title: The World Awaits, Start Exploring
description: "Master stress-free travel with expert coaching! Learn how to plan seamless trips, enjoy every journey without the hassle. Get personalized strategies, packing tips, and travel hacks to make your adventures smooth and worry-free. Start traveling smarter today!"
keywords: "stress-free travel, travel coaching, how to travel without stress, travel planning tips, smooth travel experience, travel without anxiety, hassle-free travel, travel anxiety coach, personalized travel coaching"
email: planyourworldtrip@gmail.com
url: "https://planyourworldtrip.com" # the base hostname & protocol for your site
baseurl: ""

author: "Travel Coach Expert"

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

